#base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.30.0/controller.yaml

  - flannel

  #- https://raw.githubusercontent.com/traefik/traefik/v3.5/docs/content/reference/dynamic-configuration/kubernetes-crd-definition-v1.yml
  - https://raw.githubusercontent.com/traefik/traefik/v3.5/docs/content/reference/dynamic-configuration/kubernetes-crd-rbac.yml
  - https://github.com/traefik/traefik-helm-chart/releases/download/v37.2.0/traefik.yaml

  - traefik
  - argocd
  - longhorn
  - longhorn/encrypted.yaml
